name: yandex_dictionary_api
description: Package to access the Yandex.Dictionary API over HTTP.
version: 1.0.2
homepage: https://github.com/tyypgzl/yandex_dictionary_api
issue_tracker: https://github.com/tyypgzl/yandex_dictionary_api/issues
topics:
  - api
  - yandex
  - dictionary

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: ^1.1.0

dev_dependencies:
  test: ^1.19.2
  very_good_analysis: ^5.1.0
